Repository opendevstack/ods-core, pull requests merged in 2020-07, with the labels that each got.

#669 update readme for latest changes
  README.md
Labels: documentation

#676 Allow to customize Bitbucket project name
  ods-setup/repos.sh
Labels: enhancement

#677 ods-verify: parameterize bitbucket project and ocp one
  .gitignore
  tests/.gitignore
  tests/Makefile
  tests/create-projects/create-cd-jenkins_test.go
  tests/create-projects/create-projects_test.go
  tests/create-projects/jenkinsfile_test.go
  tests/go.mod
  tests/go.sum
  tests/installation-test.sh
  tests/utils/clean-up.go
Labels: enhancement

#682 Make BB project for config repo configurable
  ods-setup/config.sh
Labels: bug

#683 Configure ODS_NAMESPACE and ODS_BITBUCKET_PROJECT
  ods-provisioning-app/ocp-config/cm.yml
Labels: bug

#685 Feature/add jenkins json golden check
  tests/Makefile
  tests/create-projects/golden/jenkins-create-project-stages.json
  tests/create-projects/jenkinsfile_test.go
  tests/scripts/utils/print-jenkins-json-status.sh
  tests/scripts/utils/print-jenkins-log.sh
Labels: enhancement

#688 Put Sonar info into Jenkins master
  jenkins/master/Dockerfile
  jenkins/ocp-config/build/bc.yml
Labels: enhancement

#684 Add scheme to retrieved host
  Makefile
  jenkins/master/configuration/init.groovy.d/url.groovy
  ods-devenv/scripts/deploy.sh
Labels: bug

#691 Update proxy.groovy
  jenkins/master/configuration/init.groovy.d/proxy.groovy
Labels: bug

#694 Log non-successful return code when triggering pipeline
  jenkins/webhook-proxy/main.go
  jenkins/webhook-proxy/main_test.go
Labels: bug

#701 Fix Jenkins master issues
  jenkins/master/configuration/init.groovy.d/proxy.groovy
  jenkins/master/configuration/init.groovy.d/url.groovy
  jenkins/master/ods-run
  jenkins/master/plugins.txt
Labels: bug

#703 fix wrong config map param
  configuration-sample/ods-core.env.sample
  ods-provisioning-app/ocp-config/cm.yml
Labels: bug

#704 Fix provisioning app auth config in ods-core.env
  ods-devenv/scripts/deploy.sh
Labels: enhancement

#706 always get tagged image - latest version
  jenkins/ocp-config/build/bc.yml
  ods-document-generation-svc/ocp-config/bc.yml
  ods-provisioning-app/ocp-config/bc.yml
  sonarqube/ocp-config/sonarqube.yml
Labels: enhancement

#711 Feature/add prov app test - including delete ...
  .gitignore
  tests/ods-verify/golden/create-project-request.json
  tests/ods-verify/golden/create-project-response.json
  tests/ods-verify/verify-ods-project-provision-api_test.go
  tests/scripts/create-project-api.sh
  tests/utils/clean-up.go
  tests/verify.sh
Labels: enhancement

#715 Remove outdated docs
  docs/modules/administration/assets/images/documentation/openshift/shared-lib-1.PNG
  docs/modules/administration/assets/images/documentation/openshift/shared-lib-2.PNG
  docs/modules/administration/assets/images/documentation/prepare-script/activate-sso.PNG
  docs/modules/administration/assets/images/documentation/prepare-script/directory-listing.PNG
  docs/modules/administration/assets/images/documentation/prepare-script/git-credentials.PNG
  docs/modules/administration/assets/images/documentation/prepare-script/jenkins-slaves.PNG
  docs/modules/administration/assets/images/documentation/rundeck/import-remote-changes.PNG
  docs/modules/administration/assets/images/documentation/rundeck/jobs.PNG
  docs/modules/administration/assets/images/documentation/rundeck/project.PNG
  docs/modules/administration/assets/images/documentation/rundeck/remote-changes.PNG
  docs/modules/administration/assets/images/documentation/rundeck/rundeck-login.PNG
  docs/modules/administration/assets/images/documentation/rundeck/verify-connections.PNG
  docs/modules/administration/assets/images/documentation/setup-script/clone_repo.PNG
  docs/modules/administration/assets/images/documentation/setup-script/script-execution-1.PNG
  docs/modules/administration/assets/images/documentation/setup-script/script-execution-2.PNG
  docs/modules/administration/assets/images/documentation/setup-script/script-execution-3.PNG
  docs/modules/administration/assets/images/documentation/setup-script/scripts.PNG
  docs/modules/administration/assets/images/documentation/setup-script/setup_finished.PNG
  docs/modules/administration/assets/images/documentation/setup-script/stack-confirm.PNG
  docs/modules/administration/assets/images/documentation/sonarqube/apptoken.PNG
  docs/modules/administration/assets/images/documentation/sonarqube/pause-script.PNG
  docs/modules/administration/assets/images/documentation/sonarqube/sonar_qube_user.PNG
  docs/modules/administration/assets/images/documentation/sonarqube/sonarqube_login.PNG
  docs/modules/administration/assets/images/documentation/sonarqube/sonarqube_my_account.PNG
  docs/modules/administration/pages/install-guide.adoc
  docs/modules/administration/pages/local-install-requirements.adoc
Labels: documentation

#717 Bump Tailor to 1.1.4
  create-projects/tests/run.sh
  docs/modules/administration/pages/installation.adoc
  docs/modules/administration/pages/update-2-to-3.adoc
  jenkins/agent-base/Dockerfile
  ods-devenv/README.md
  ods-devenv/scripts/deploy.sh
Labels: enhancement

#719 Read ODS_NAMESPACE from config
  Makefile
  docs/modules/administration/pages/installation.adoc
  ods-setup/bitbucket.sh
  scripts/get-config-param.sh
Labels: enhancement

#720 Webhook Proxy config: set Bitbucket project explicitly
  create-projects/Jenkinsfile
  create-projects/create-cd-jenkins.sh
  create-projects/tests/run.sh
  jenkins/ocp-config/deploy/jenkins-webhook-proxy.yml
Labels: enhancement

#734 Update roadmap with new frontend UI info
  docs/modules/getting-started/pages/index.adoc
Labels: documentation
