Repository opendevstack/ods-core, pull requests merged in 2020-08, with the labels that each got.

#743 (Tests) respect bitbucket project during tests
  tests/create-projects/create-cd-jenkins_test.go
  tests/utils/clean-up.go
Labels: Tests

#745 Bug/ods bb repo and namespace during create jenkins test missing
  tests/README.md
  tests/create-projects/jenkinsfile_test.go
Labels: Tests

#746 Fix various test issues
  scripts/get-config-param.sh
  tests/installation-test.sh
  tests/ods-verify/verify-ods-namespace-ocp_test.go
  tests/scripts/create-project-api.sh
  tests/verify.sh
Labels: bug

#753 Set memory request to realistic value
  jenkins/ocp-config/deploy/jenkins-master.yml
Labels: enhancement

#759 Add BuildConfig and fix retrieval of proxy vars
  Makefile
  configuration-sample/ods-core.env.sample
  nexus/configure.sh
  nexus/docker/Dockerfile
  nexus/ocp-config/bc.yml
  nexus/ocp-config/dc.yml
  nexus/ocp-config/is.yml
  sonarqube/ocp-config/sonarqube.yml
Labels: bug

#761 Pass --insecure flag from make targets
  Makefile
Labels: enhancement

#762 Do not fail when default password removal returns exit code 129
  nexus/configure.sh
Labels: bug

#765 add 20mi min storage - for prov app pvc
  ods-provisioning-app/ocp-config/Tailorfile
  ods-provisioning-app/ocp-config/pvc.yml
Labels: bug

#768 bug/delete components job broken
  create-projects/Jenkinsfile
  delete-components/Jenkinsfile
  delete-projects/Jenkinsfile
Labels: bug

#784 Pass component to delete
  tests/utils/provisioning.go
Labels: bug

#789 Ignore error when build config does not exist during deletion
  tests/utils/clean-up.go
Labels: bug

#793 Increase quickstarter test timeout to 3 hours
  tests/quickstarter-test.sh
Labels: bug
