Repository opendevstack/ods-core, pull requests merged in 2020-06, with the labels that each got.

#614 Add script to manage Bitbucket ODS project and repos
  Makefile
  docs/modules/administration/nav.adoc
  docs/modules/administration/pages/installation.adoc
  ods-setup/bitbucket.sh
Labels: enhancement

#615 Improve shell scripts
  docs/modules/administration/pages/installation.adoc
  nexus/configure.sh
  nexus/test.sh
  sonarqube/configure.sh
  sonarqube/test.sh
Labels: enhancement

#616 Specify Jenkins CPU resources
  jenkins/ocp-config/deploy/jenkins-master.yml
Labels: bug

#617 SonarQube migration
  docs/modules/administration/pages/update.adoc
  sonarqube/backup.sh
Labels: documentation

#622 write sq tokens
  sonarqube/configure.sh
Labels: enhancement

#627 Write updated SQ config values to ods-core.env
  docs/modules/administration/pages/installation.adoc
  sonarqube/configure.sh
Labels: enhancement

#631 get back be-gateway-nginx quickstarter
  ods-provisioning-app/ocp-config/cm.yml
Labels: bug

#644 run quickstarter tests after setup
  ods-devenv/scripts/deploy.sh
  tests/Makefile
  tests/install.sh
  tests/scripts/json/create-cluster-role.json
  tests/scripts/json/daemon.json
Labels: enhancement
