Repository opendevstack/ods-core, pull requests merged in 2020-12, with the labels that each got.

#909 add logs on provision app test error
  tests/scripts/provisioning-app-api.sh
  tests/utils/provisioning.go
Labels: enhancement

#887 Allow to customize sharedLibraryRef and agentImageTag in tests
  tests/quickstarter/quickstarter_test.go
  tests/quickstarter/steps.go
Labels: enhancement

#904 Refactor test targets
  nexus/test.sh
  sonarqube/test.sh
  tests/.gitignore
  tests/Makefile
  tests/README.md
  tests/create-projects-test.sh
  tests/smoke-test.sh
  tests/smoketest/provision-api_test.go
  tests/verify.sh
Labels: enhancement

#911 bug/fix smoke test file locations - master
  tests/smoketest/fixtures/create-component-request.json
  tests/smoketest/fixtures/create-project-request.json
  tests/smoketest/golden/jenkins-stages-provision-component.json
  tests/smoketest/golden/jenkins-stages-provision-project.json
  tests/utils/provisioning.go
Labels: bug

#912 increase route timeout prov app - master
  ods-provisioning-app/ocp-config/route.yml
  tests/utils/jenkins.go
Labels: bug

#914 Add separate Jenkins Master Dockerfile for UBI8
  .github/workflows/continuous-integration-workflow.yml
  configuration-sample/ods-core.env.sample
  jenkins/master/Dockerfile.rhel7
  jenkins/master/Dockerfile.ubi8
  jenkins/ocp-config/build/bc.yml
Labels: openshift4

#915 Add separate Jenkins Master Dockerfile for UBI8 (3.x)
  .github/workflows/continuous-integration-workflow.yml
  configuration-sample/ods-core.env.sample
  jenkins/master/Dockerfile.rhel7
  jenkins/master/Dockerfile.ubi8
  jenkins/ocp-config/build/bc.yml
Labels: openshift4

#917 Allow to parallelize quickstarter tests
  tests/Makefile
  tests/README.md
  tests/quickstarter-test.sh
  tests/quickstarter/quickstarter_test.go
Labels: enhancement

#920 Enable quickstarter test framework to process env variables
  tests/quickstarter/quickstarter_test.go
  tests/quickstarter/steps.go
Labels: enhancement

#921 Move verification of unit tests from shell script to Go code
  tests/quickstarter/quickstarter_test.go
  tests/scripts/print-jenkins-unittest-results.sh
  tests/scripts/verify-jenkins-unittest-results.sh
Labels: bug

#924 Fix installation of SOPS
  jenkins/agent-base/Dockerfile.rhel7
  jenkins/agent-base/Dockerfile.ubi8
Labels: bug

#918 Normalize LF for ods-core.env files
  .gitattributes
Labels: enhancement

#928 Update intro docs
  docs/modules/getting-started/pages/index.adoc
Labels: documentation
