Repository opendevstack/ods-core, pull requests merged in 2021-01, with the labels that each got.

#932 Reference oc Git commit 3.9 instead of yanked tag
  tests/go.mod
  tests/go.sum
Labels: bug

#935 Add update guides to 4.x
  docs/modules/update-guides/nav.adoc
  docs/modules/update-guides/pages/4x.adoc
Labels: documentation

#938 linked contributing text to PMC repo
  docs/modules/contributing/images/contribution-flow.plantuml
  docs/modules/contributing/images/contribution-flow.png
  docs/modules/contributing/pages/development.adoc
Labels: skip changelog
